# .github/workflows/deploy.yml (文件名可以自定义，但建议放在 .github/workflows/)

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 18 * * *'




jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      # 如果你的网站是静态的，或者不需要构建步骤，你可以跳过以下步骤
      # 如果你使用 Jekyll 或其他静态网站生成器，这里可能需要对应的构建步骤
      # 例如，对于 Jekyll：
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4' # 根据你的 Jekyll 需求调整
          bundler-cache: true # installs dependencies with bundler
      - name: Install Jekyll and dependencies
        run: bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build --destination ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site' # 你的网站生成后的目录，对于 Jekyll 通常是 _site，对于纯静态文件可能是 . 或 public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
